import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--bg-canvas)',
        surface: {
          DEFAULT: 'var(--bg-surface)',
          elevated: 'var(--bg-surface-elevated)',
          muted: 'var(--bg-surface-muted)',
          dark: 'var(--bg-surface-dark)',
        },
        espresso: {
          50: 'var(--color-espresso-50)',
          100: 'var(--color-espresso-100)',
          200: 'var(--color-espresso-200)',
          300: 'var(--color-espresso-300)',
          400: 'var(--color-espresso-400)',
          500: 'var(--color-espresso-500)',
          600: 'var(--color-espresso-600)',
          700: 'var(--color-espresso-700)',
          800: 'var(--color-espresso-800)',
          900: 'var(--color-espresso-900)',
          950: 'var(--color-espresso-950)',
        },
        cream: {
          300: 'var(--color-cream-300)',
          400: 'var(--color-cream-400)',
          500: 'var(--color-cream-500)',
          600: 'var(--color-cream-600)',
          700: 'var(--color-cream-700)',
          800: 'var(--color-cream-800)',
          900: 'var(--color-cream-900)',
        },
        terracotta: {
          50: 'var(--color-terracotta-50)',
          100: 'var(--color-terracotta-100)',
          200: 'var(--color-terracotta-200)',
          300: 'var(--color-terracotta-300)',
          400: 'var(--color-terracotta-400)',
          500: 'var(--color-terracotta-500)',
          600: 'var(--color-terracotta-600)',
          700: 'var(--color-terracotta-700)',
          800: 'var(--color-terracotta-800)',
          900: 'var(--color-terracotta-900)',
        },
        olive: {
          100: 'var(--color-olive-100)',
          200: 'var(--color-olive-200)',
          300: 'var(--color-olive-300)',
          400: 'var(--color-olive-400)',
          500: 'var(--color-olive-500)',
          600: 'var(--color-olive-600)',
          700: 'var(--color-olive-700)',
        },
        honey: {
          100: 'var(--color-honey-100)',
          200: 'var(--color-honey-200)',
          300: 'var(--color-honey-300)',
          400: 'var(--color-honey-400)',
          500: 'var(--color-honey-500)',
          600: 'var(--color-honey-600)',
          700: 'var(--color-honey-700)',
        },
        berry: {
          100: 'var(--color-berry-100)',
          200: 'var(--color-berry-200)',
          300: 'var(--color-berry-300)',
          400: 'var(--color-berry-400)',
          500: 'var(--color-berry-500)',
          600: 'var(--color-berry-600)',
          700: 'var(--color-berry-700)',
        },
        charcoal: {
          100: 'var(--color-charcoal-100)',
          200: 'var(--color-charcoal-200)',
          300: 'var(--color-charcoal-300)',
          400: 'var(--color-charcoal-400)',
          500: 'var(--color-charcoal-500)',
          600: 'var(--color-charcoal-600)',
          700: 'var(--color-charcoal-700)',
          800: 'var(--color-charcoal-800)',
          900: 'var(--color-charcoal-900)',
        },
      },
      textColor: {
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        muted: 'var(--text-muted)',
        'on-dark': 'var(--text-on-dark)',
        accent: 'var(--text-accent)',
      },
      borderColor: {
        subtle: 'var(--border-subtle)',
        medium: 'var(--border-medium)',
        strong: 'var(--border-strong)',
        dark: 'var(--border-dark)',
      },
      fontFamily: {
        serif: ['var(--font-serif)', 'serif'],
        sans: ['var(--font-sans)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        subtle: 'var(--shadow-subtle)',
        card: 'var(--shadow-card)',
        elevated: 'var(--shadow-elevated)',
        drawer: 'var(--shadow-drawer)',
        modal: 'var(--shadow-modal)',
      },
    },
  },
  plugins: [],
};

export default config;
